In [186]:
import numpy as np
import cv2
import matplotlib.pyplot as plt

def load(fn):
    img = cv2.imread("../assets/" + fn)
    img = img[..., ::-1]
    return img 

def show(img):
    plt.imshow(img)
    
img128 = load("imori.jpg")
img = load("imori_256x256.png")
nimg = load("imori_256x256_noise.png")
dimg = load("imori_256x256_dark.png")
gimg = load("imori_256x256_gamma.png")


In [4]:


# 画像の読み込み
img = cv2.imread("../assets/imori.jpg")

# 画像の表示
plt.imshow(img)




In [5]:
plt.show()


In [7]:
img = img[..., ::-1]
plt.imshow(img)
plt.show()

In [8]:
img = cv2.imread("../assets/imori.jpg")
img = img[..., ::-1]

plt.imshow(img)
plt.show()

In [9]:


print('min =', img.min())
print('max =', img.max())



min = 0
max = 255


In [10]:
img


array([[[ 67,  80, 132],
        [ 39,  55, 104],
        [ 36,  54, 100],
        ...,
        [110, 109, 175],
        [ 70,  88, 134],
        [100, 126, 163]],

       [[ 71,  88, 140],
        [ 52,  65, 117],
        [ 47,  54, 106],
        ...,
        [135, 139, 177],
        [123, 137, 176],
        [ 91, 110, 152]],

       [[ 69,  85, 137],
        [ 66,  77, 131],
        [ 60,  67, 119],
        ...,
        [148, 155, 207],
        [159, 179, 232],
        [ 82, 104, 161]],

       ...,

       [[152, 172, 231],
        [ 80,  97, 153],
        [ 97, 107, 160],
        ...,
        [ 38,  55, 107],
        [ 38,  60, 101],
        [ 36,  59,  93]],

       [[176, 198, 255],
        [ 95, 114, 172],
        [104, 116, 168],
        ...,
        [ 58,  76, 150],
        [ 35,  59, 119],
        [ 33,  58, 112]],

       [[130, 154, 214],
        [109, 130, 187],
        [112, 124, 176],
        ...,
        [ 94, 117, 185],
        [ 71,  98, 151],
        [ 39,  70, 116]]

In [11]:
r = img[..., 0]
g = img[..., 1]
b = img[..., 2]

In [12]:
r

array([[ 67,  39,  36, ..., 110,  70, 100],
       [ 71,  52,  47, ..., 135, 123,  91],
       [ 69,  66,  60, ..., 148, 159,  82],
       ...,
       [152,  80,  97, ...,  38,  38,  36],
       [176,  95, 104, ...,  58,  35,  33],
       [130, 109, 112, ...,  94,  71,  39]], dtype=uint8)

In [13]:
g

array([[ 80,  55,  54, ..., 109,  88, 126],
       [ 88,  65,  54, ..., 139, 137, 110],
       [ 85,  77,  67, ..., 155, 179, 104],
       ...,
       [172,  97, 107, ...,  55,  60,  59],
       [198, 114, 116, ...,  76,  59,  58],
       [154, 130, 124, ..., 117,  98,  70]], dtype=uint8)

In [14]:
b

array([[132, 104, 100, ..., 175, 134, 163],
       [140, 117, 106, ..., 177, 176, 152],
       [137, 131, 119, ..., 207, 232, 161],
       ...,
       [231, 153, 160, ..., 107, 101,  93],
       [255, 172, 168, ..., 150, 119, 112],
       [214, 187, 176, ..., 185, 151, 116]], dtype=uint8)

In [15]:

plt.subplot(1, 3, 1)
plt.title('R')
plt.imshow(r, cmap='gray')
plt.subplot(1, 3, 2)
plt.title('G')
plt.imshow(g, cmap='gray')
plt.subplot(1, 3, 3)
plt.title('B')
plt.imshow(b, cmap='gray')
plt.show()

In [16]:
img.shape

(128, 128, 3)

In [17]:
_img = img.astype(np.float32)
_img.dtype

dtype('float32')

In [18]:


plt.imshow(_img)
plt.show()



Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).


In [19]:


_img /= 255
plt.imshow(_img)
plt.show()



In [20]:
_img

array([[[0.2627451 , 0.3137255 , 0.5176471 ],
        [0.15294118, 0.21568628, 0.40784314],
        [0.14117648, 0.21176471, 0.39215687],
        ...,
        [0.43137255, 0.42745098, 0.6862745 ],
        [0.27450982, 0.34509805, 0.5254902 ],
        [0.39215687, 0.49411765, 0.6392157 ]],

       [[0.2784314 , 0.34509805, 0.54901963],
        [0.20392157, 0.25490198, 0.45882353],
        [0.18431373, 0.21176471, 0.41568628],
        ...,
        [0.5294118 , 0.54509807, 0.69411767],
        [0.48235294, 0.5372549 , 0.6901961 ],
        [0.35686275, 0.43137255, 0.59607846]],

       [[0.27058825, 0.33333334, 0.5372549 ],
        [0.25882354, 0.3019608 , 0.5137255 ],
        [0.23529412, 0.2627451 , 0.46666667],
        ...,
        [0.5803922 , 0.60784316, 0.8117647 ],
        [0.62352943, 0.7019608 , 0.9098039 ],
        [0.32156864, 0.40784314, 0.6313726 ]],

       ...,

       [[0.59607846, 0.6745098 , 0.90588236],
        [0.3137255 , 0.38039216, 0.6       ],
        [0.38039216, 0

In [21]:
img[20, 30]

array([171, 178, 232], dtype=uint8)

In [22]:
img[20, 30, 1]

178

In [23]:
img[20, 30:33]

array([[171, 178, 232],
       [153, 156, 209],
       [ 77,  85, 134]], dtype=uint8)

In [25]:
img2 = img.copy()
img2[:50, :50] = 0
plt.imshow(img2)
plt.show()



In [27]:
img2 = img.copy().astype(np.float32)
img2[60:160, 60:160, 2] = 260
img2 = img2.astype(np.uint8)
plt.imshow(img2)
plt.show()

In [28]:
cv2.imwrite('sample.png', img2)


True

In [29]:
plt.imshow(img)
plt.savefig('sample.png')

In [31]:


img3 = img.copy()


In [32]:
img3.shape

(128, 128, 3)

In [33]:
h, w, c = img3.shape
img3[: h // 2, : w // 2] = img3[: h // 2, : w // 2, ::-1]
plt.imshow(img3)
plt.show()

In [35]:
import cv2
img = cv2.imread("../assets/imori.jpg")


In [37]:
img


array([[[132,  80,  67],
        [104,  55,  39],
        [100,  54,  36],
        ...,
        [175, 109, 110],
        [134,  88,  70],
        [163, 126, 100]],

       [[140,  88,  71],
        [117,  65,  52],
        [106,  54,  47],
        ...,
        [177, 139, 135],
        [176, 137, 123],
        [152, 110,  91]],

       [[137,  85,  69],
        [131,  77,  66],
        [119,  67,  60],
        ...,
        [207, 155, 148],
        [232, 179, 159],
        [161, 104,  82]],

       ...,

       [[231, 172, 152],
        [153,  97,  80],
        [160, 107,  97],
        ...,
        [107,  55,  38],
        [101,  60,  38],
        [ 93,  59,  36]],

       [[255, 198, 176],
        [172, 114,  95],
        [168, 116, 104],
        ...,
        [150,  76,  58],
        [119,  59,  35],
        [112,  58,  33]],

       [[214, 154, 130],
        [187, 130, 109],
        [176, 124, 112],
        ...,
        [185, 117,  94],
        [151,  98,  71],
        [116,  70,  39]]

In [38]:
plt.imshow(img)


In [39]:
img = img[..., ::-1]



In [41]:
plt.imshow(img)

In [2]:
def load(fn):
    img = cv2.imread("../assets/" + fn)
    img = img[..., ::-1]
    return img 

def show(img):
    plt.imshow(img)

In [7]:
#Q1
img = load("imori.jpg")
show(img)

In [8]:
img2 = img.copy()
img2[:,:,0] = img[:,:,2]
img2[:,:,2] = img[:,:,0]
show(img2)

In [47]:
#Q2
gs = img.copy()


In [52]:
gs.shape


(128, 128, 3)

In [53]:
for r in range(gs.shape[0]):
    for w in range(gs.shape[1]):
        gs[r,w] = gs[r,w,0] * 0.2126 + gs[r,w,1]*0.7152 + gs[r,w,2]*0.0722
    

In [54]:
show(gs)

In [9]:
gs = img.copy()
show(gs)

In [56]:
r = gs[:,:,0]

In [57]:
r

array([[ 67,  39,  36, ..., 110,  70, 100],
       [ 71,  52,  47, ..., 135, 123,  91],
       [ 69,  66,  60, ..., 148, 159,  82],
       ...,
       [152,  80,  97, ...,  38,  38,  36],
       [176,  95, 104, ...,  58,  35,  33],
       [130, 109, 112, ...,  94,  71,  39]], dtype=uint8)

In [10]:
r = gs[:,:,0].copy()
g = gs[:,:,1].copy()
b = gs[:,:,2].copy()

gss = r*0.2126 + g*0.7152 + b*0.0722

In [11]:
show(gss)

In [60]:
gss

array([[ 80.9906,  55.1362,  53.4944, ..., 113.9778,  87.4944, 123.1438],
       [ 88.1402,  65.9906,  56.2662, ..., 140.8932, 136.8394, 108.993 ],
       [ 85.3528,  78.5602,  69.2662, ..., 157.2662, 178.5746, 103.4382],
       ...,
       [172.0078,  97.429 , 108.7006, ...,  55.1402,  58.283 ,  56.565 ],
       [197.4382, 114.1482, 117.2032, ...,  77.516 ,  58.2296,  56.5838],
       [153.2296, 129.6508, 125.2032, ..., 117.0198,  96.0864,  66.7306]])

In [1]:
gss = gss.astype(np.uint8)
show(gss)

NameError: name 'gss' is not defined

In [80]:
gss

array([[ 90,  64,  62, ..., 123,  96, 131],
       [ 97,  75,  64, ..., 146, 144, 117],
       [ 94,  87,  77, ..., 165, 188, 114],
       ...,
       [183, 107, 117, ...,  64,  67,  64],
       [208, 124, 126, ...,  90,  70,  67],
       [165, 140, 134, ..., 129, 107,  77]], dtype=uint8)

In [65]:
gss.min

<function ndarray.min>

In [66]:
gss.min()

6

In [67]:
gss.max()


254

In [82]:
show([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
cv2.imshow("result", gss)

In [12]:
#q3
gs = img.copy()
for r in range(gs.shape[0]):
    for w in range(gs.shape[1]):
        val = gs[r,w,0] * 0.2126 + gs[r,w,1]*0.7152 + gs[r,w,2]*0.0722
        if val < 128:
            gs[r,w]=0
        else:
            gs[r,w]=255

In [13]:
show(gs)

In [3]:
p=np.array([[1,2,3],[4,5,6]])

In [5]:
p=p[:,0]*2+p[:,1]*3

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [6]:
p

array([ 8, 23])

In [7]:
p=np.array([[1,2,3],[4,5,6]])

In [8]:
p

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
p[:,0]

array([1, 4])

In [10]:
p[...,0]

array([1, 4])

In [11]:
p[:,0]+p[:,1]

array([3, 9])

In [12]:
p=np.array([[1,2,3],[4,5,6]])

In [13]:
show(p)

In [14]:
p


array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
r = img[:,:,0].copy()
g = img[:,:,1].copy()
b = img[:,:,2].copy()

gss = r*0.2126 + g*0.7152 + b*0.0722

NameError: name 'img' is not defined

In [16]:
img = load("imori.jpg")


In [17]:
show(img)

In [18]:
r = img[:,:,0].copy()
g = img[:,:,1].copy()
b = img[:,:,2].copy()

gss = r*0.2126 + g*0.7152 + b*0.0722

In [19]:
show(gss)

In [20]:
gss

array([[ 80.9906,  55.1362,  53.4944, ..., 113.9778,  87.4944, 123.1438],
       [ 88.1402,  65.9906,  56.2662, ..., 140.8932, 136.8394, 108.993 ],
       [ 85.3528,  78.5602,  69.2662, ..., 157.2662, 178.5746, 103.4382],
       ...,
       [172.0078,  97.429 , 108.7006, ...,  55.1402,  58.283 ,  56.565 ],
       [197.4382, 114.1482, 117.2032, ...,  77.516 ,  58.2296,  56.5838],
       [153.2296, 129.6508, 125.2032, ..., 117.0198,  96.0864,  66.7306]])

In [22]:
gss =gss.astype(np.uint8)

In [23]:
show(gss)

In [24]:
gs = img.copy()

In [26]:
gs[:,:,0] = gss[:,:]
gs[:,:,1] = gss[:,:]
gs[:,:,2] = gss[:,:]

In [27]:
gs

array([[[ 80,  80,  80],
        [ 55,  55,  55],
        [ 53,  53,  53],
        ...,
        [113, 113, 113],
        [ 87,  87,  87],
        [123, 123, 123]],

       [[ 88,  88,  88],
        [ 65,  65,  65],
        [ 56,  56,  56],
        ...,
        [140, 140, 140],
        [136, 136, 136],
        [108, 108, 108]],

       [[ 85,  85,  85],
        [ 78,  78,  78],
        [ 69,  69,  69],
        ...,
        [157, 157, 157],
        [178, 178, 178],
        [103, 103, 103]],

       ...,

       [[172, 172, 172],
        [ 97,  97,  97],
        [108, 108, 108],
        ...,
        [ 55,  55,  55],
        [ 58,  58,  58],
        [ 56,  56,  56]],

       [[197, 197, 197],
        [114, 114, 114],
        [117, 117, 117],
        ...,
        [ 77,  77,  77],
        [ 58,  58,  58],
        [ 56,  56,  56]],

       [[153, 153, 153],
        [129, 129, 129],
        [125, 125, 125],
        ...,
        [117, 117, 117],
        [ 96,  96,  96],
        [ 66,  66,  66]]

In [28]:
show(gs)

In [24]:
#Q2
def gray_scale(imag):
    r = imag[:,:,0].copy()
    g = imag[:,:,1].copy()
    b = imag[:,:,2].copy()

    gss = r*0.2126 + g*0.7152 + b*0.0722
    gs = imag.copy()
    gs[:,:,0] = gss[:,:]
    gs[:,:,1] = gss[:,:]
    gs[:,:,2] = gss[:,:]
    return gs

show(gray_scale(img))


def gray_scale_single(imag):
    r = imag[:,:,0].copy()
    g = imag[:,:,1].copy()
    b = imag[:,:,2].copy()

    return (r*0.2126 + g*0.7152 + b*0.0722).astype(np.uint8)

def gray_scale_triple(gimag):
    t = np.zeros([gimag.shape[0], gimag.shape[1], 3]).astype(np.uint8)
    t[:,:,0] = gimag
    t[:,:,1] = gimag
    t[:,:,2] = gimag
    return t


In [37]:
#Q3
def binary(imag):
    gs = gray_scale(imag)
    binimg = gs >=128
    binimg = binimg*255
    return binimg.astype(np.uint8)
def binary2(imag):
    gs = gray_scale(imag)
    binimg = np.minimum(gs//128, 1)*255
    return binimg.astype(np.uint8)
show(binary(img))

In [53]:
max_sigma = -1
max_th = -1
ot = img.copy()
for th in range(256):
    r = img[:,:,0].copy()
    g = img[:,:,1].copy()
    b = img[:,:,2].copy()

    gss = r*0.2126 + g*0.7152 + b*0.0722
    gss = gss.astype(np.uint8)
    w0 = np.sum(gss < th)
    w1 = np.sum(gss >= th)
    c0 = (gss * (gss < th))
    c0 = c0.astype(np.float)
    c1 = (gss * (gss >= th))
    c1 = c1.astype(np.float)
    M0 = np.sum(c0) / np.size(c0)
    M1 = np.sum(c1) / np.size(c1)
    sigma_b_two = 1.0 * w0 * w1 * (M0-M1)*(M0-M1)/((w0+w1)*(w0+w1))
    if max_sigma < sigma_b_two:
        max_sigma = sigma_b_two
        max_th = th
        
max_th

83

In [71]:
#Q4
def otsu_binary0(imag):  
    max_sigma = -1
    max_th = -1
    ot = imag.copy()
    for th in range(256):
        r = imag[:,:,0].copy()
        g = imag[:,:,1].copy()
        b = imag[:,:,2].copy()

        gss = r*0.2126 + g*0.7152 + b*0.0722
        gss = gss.astype(np.uint8)
        w0 = np.sum(gss < th)
        w1 = np.sum(gss >= th)
        c0 = (gss * (gss < th)).astype(np.float)
        c1 = (gss * (gss >= th)).astype(np.float)
        if w0 == 0 or w1 == 0:
            continue
        M0 = np.sum(c0) / w0
        M1 = np.sum(c1) / w1
        sigma_b_two = 1.0 * w0 * w1 * (M0-M1)*(M0-M1) #/((w0+w1)*(w0+w1))
        if max_sigma < sigma_b_two:
            max_sigma = sigma_b_two
            max_th = th
        #print(th,w0,w1,int(M0),int(M1),int(sigma_b_two))
    gs = gray_scale(imag)
    binimg = gs >= max_th
    binimg = binimg*255
    return binimg.astype(np.uint8)

def otsu_binary(imag):  
    max_sigma = -1
    max_th = -1
    ot = imag.copy()
    for th in range(256):
        r = imag[:,:,0].copy()
        g = imag[:,:,1].copy()
        b = imag[:,:,2].copy()

        gss = r*0.2126 + g*0.7152 + b*0.0722
        gss = gss.astype(np.uint8)
        w0 = np.sum(gss < th)
        w1 = np.sum(gss >= th)
        if w0 == 0 or w1 == 0:
            continue
        M0 = gss[gss < th].mean()
        M1 = gss[gss >= th].mean()
        sigma_b_two = 1.0 * w0 * w1 * (M0-M1)*(M0-M1) #/((w0+w1)*(w0+w1))
        if max_sigma < sigma_b_two:
            max_sigma = sigma_b_two
            max_th = th
        #print(th,w0,w1,int(M0),int(M1),int(sigma_b_two))
    gs = gray_scale(imag)
    binimg = gs >= max_th
    binimg = binimg*255
    return binimg.astype(np.uint8)

show(otsu_binary(img))

In [57]:
img = load("imori_256x256.png")

In [74]:
x = np.array([[1,2,3],[4,5,6]])

In [75]:
x[x>2]

array([3, 4, 5, 6])

In [76]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
#Q5

show(img)

In [82]:
hsvt = img.copy().astype(np.float)
hsvt = hsvt / 255.0
for i in range(256):
    for j in range(256):
        mx = hsvt[i][j].max()
        mn = hsvt[i][j].min()
        S = mx-mn
        V = mx
        r = hsvt[i][j][0]
        g = hsvt[i][j][1]
        b = hsvt[i][j][2]
        H = 0
        if mx-mn > 0:
            if mn==b:
                H = 60.0 + 60.0 *(g-r)/ (mx-mn)
            elif mn==r:
                H = 180.0 + 60.0*(b-g)/ (mx-mn)
            else:
                H = 300.0 + 60.0*(r-b) /(mx-mn)
        


In [129]:
def rgb2hsv(imag):
    hsvt = imag.copy().astype(np.float)
    hsvt = hsvt / 255.0
    for i in range(hsvt.shape[0]):
        for j in range(hsvt.shape[1]):
            mx = hsvt[i][j].max()
            mn = hsvt[i][j].min()
            r = hsvt[i][j][0]
            g = hsvt[i][j][1]
            b = hsvt[i][j][2]
            H = 0
            if mx-mn > 0:
                if mn==b:
                    H = 60.0 + 60.0 *(g-r)/ (mx-mn)
                elif mn==r:
                    H = 180.0 + 60.0*(b-g)/ (mx-mn)
                else:
                    H = 300.0 + 60.0*(r-b) /(mx-mn)
            S = mx-mn
            V = mx
            hsvt[i][j][0] = H
            hsvt[i][j][1] = S
            hsvt[i][j][2] = V

    return hsvt

def hsv2rgb(imag):
    rgbt = imag.copy().astype(np.float)
    for i in range(rgbt.shape[0]):
        for j in range(rgbt.shape[1]):
            C = rgbt[i][j][1]
            HH = rgbt[i][j][0] / 60.0
            HH_I = int(HH)
            HH_F = HH - HH_I
            X = C *(1 - np.abs(-1 + HH_F + HH_I % 2))
            V = rgbt[i][j][2]
            if HH < 1:
                R = V - C + C
                G = V - C + X
                B = V - C + 0
            elif HH < 2:
                R = V - C + X
                G = V - C + C
                B = V - C + 0 
            elif HH < 3:
                R = V - C + 0
                G = V - C + C
                B = V - C + X 
            elif HH < 4:
                R = V - C + 0
                G = V - C + X
                B = V - C + C 
            elif HH < 5:
                R = V - C + X
                G = V - C + 0
                B = V - C + C 
            elif HH < 6:
                R = V - C + C
                G = V - C + 0
                B = V - C + X
            else:
                R = V - C + 0
                G = V - C + 0
                B = V - C + 0
            rgbt[i][j][0] = R
            rgbt[i][j][1] = G
            rgbt[i][j][2] = B
    rgbt = rgbt * 255
    return rgbt.astype(np.uint8)

show(hsv2rgb(rgb2hsv(img)))
#hsv2rgb(rgb2hsv(img))
#show(img)

In [93]:
show(img)

In [94]:
hsv2rgb(rgb2hsv(img))

array([[[ 46, 137, 137],
        [ 43, 115, 115],
        [ 36,  89,  89],
        ...,
        [ 84,  84, 122],
        [115, 115, 145],
        [144, 144, 169]],

       [[ 69, 134, 134],
        [ 59, 121, 121],
        [ 43,  92,  92],
        ...,
        [ 79, 136, 136],
        [102, 158, 158],
        [119, 177, 177]],

       [[ 74, 144, 144],
        [ 60, 138, 138],
        [ 51, 112, 112],
        ...,
        [104, 165, 165],
        [ 90, 163, 163],
        [ 89, 171, 171]],

       ...,

       [[169, 255, 255],
        [134, 240, 240],
        [ 91, 196, 196],
        ...,
        [ 41, 128, 128],
        [ 36, 116, 116],
        [ 35, 110, 110]],

       [[119, 241, 241],
        [ 96, 219, 219],
        [ 89, 198, 198],
        ...,
        [ 52, 129, 129],
        [ 45, 123, 123],
        [ 43, 120, 120]],

       [[ 96, 201, 201],
        [114, 200, 200],
        [111, 181, 181],
        ...,
        [ 66, 141, 141],
        [ 51, 135, 135],
        [ 52, 140, 140]]

In [98]:
bw = np.array([
    [[0,0,0],[0,0,0]],
    [[255,255,255],[255,255,255]]
])
show(bw)

In [99]:
rgb2hsv(bw)

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 1.],
        [0., 0., 1.]]])

In [101]:
show(hsv2rgb(rgb2hsv(bw)))

In [102]:
sm = np.array([[[50,100,150]]])

In [103]:
rgb2hsv(sm)

array([[[210.        ,   0.39215686,   0.58823529]]])

In [105]:
show(hsv2rgb(rgb2hsv(sm)))

In [106]:
show(sm)

In [118]:
sm = np.array([[[140,160,150]]])
print(sm)
print(rgb2hsv(sm))
print(hsv2rgb(rgb2hsv(sm)))

[[[140 160 150]]]
[[[1.50000000e+02 7.84313725e-02 6.27450980e-01]]]
[[[140 160 140]]]


In [119]:
sm = np.array([[[150,160,140]]])
print(sm)
print(rgb2hsv(sm))
print(hsv2rgb(rgb2hsv(sm)))

[[[150 160 140]]]
[[[9.00000000e+01 7.84313725e-02 6.27450980e-01]]]
[[[160 160 140]]]


In [120]:
sm = np.array([[[160,150,140]]])
print(sm)
print(rgb2hsv(sm))
print(hsv2rgb(rgb2hsv(sm)))

[[[160 150 140]]]
[[[30.          0.07843137  0.62745098]]]
[[[160 140 140]]]


In [127]:
sm = np.array([[[160,140,150]]])
print(sm)
print(rgb2hsv(sm))
print(hsv2rgb(rgb2hsv(sm)))

[[[160 140 150]]]
[[[3.30000000e+02 7.84313725e-02 6.27450980e-01]]]
0.07843137254901955 5.5 0.07843137254901955 0.6274509803921569 0.6274509803921569 0.5490196078431373 0.6274509803921569
[[[160 140 160]]]


In [126]:
sm = np.array([[[160,140,160]]])
print(sm)
print(rgb2hsv(sm))
print(hsv2rgb(rgb2hsv(sm)))

[[[160 140 160]]]
[[[3.00000000e+02 7.84313725e-02 6.27450980e-01]]]
0.07843137254901955 5.0 0.07843137254901955 0.6274509803921569 0.6274509803921569 0.5490196078431373 0.6274509803921569
[[[160 140 160]]]


In [137]:
#Q5
def rgb2hsv(imag):
    hsvt = imag.copy().astype(np.float)
    hsvt = hsvt / 255.0
    for i in range(hsvt.shape[0]):
        for j in range(hsvt.shape[1]):
            mx = hsvt[i][j].max()
            mn = hsvt[i][j].min()
            r = hsvt[i][j][0]
            g = hsvt[i][j][1]
            b = hsvt[i][j][2]
            H = 0
            if mx-mn > 0:
                if mn==b:
                    H = 60.0 + 60.0 *(g-r)/ (mx-mn)
                elif mn==r:
                    H = 180.0 + 60.0*(b-g)/ (mx-mn)
                else:
                    H = 300.0 + 60.0*(r-b) /(mx-mn)
            S = mx-mn
            V = mx
            hsvt[i][j][0] = H
            hsvt[i][j][1] = S
            hsvt[i][j][2] = V

    return hsvt

def hsv2rgb(imag):
    rgbt = imag.copy().astype(np.float)
    for i in range(rgbt.shape[0]):
        for j in range(rgbt.shape[1]):
            C = rgbt[i][j][1]
            HH = rgbt[i][j][0] / 60.0
            HH_I = int(HH)
            HH_F = HH - HH_I
            X = C *(1 - np.abs(-1 + HH_F + HH_I % 2))
            V = rgbt[i][j][2]
            if HH < 1:
                R = V - C + C
                G = V - C + X
                B = V - C + 0
            elif HH < 2:
                R = V - C + X
                G = V - C + C
                B = V - C + 0 
            elif HH < 3:
                R = V - C + 0
                G = V - C + C
                B = V - C + X 
            elif HH < 4:
                R = V - C + 0
                G = V - C + X
                B = V - C + C 
            elif HH < 5:
                R = V - C + X
                G = V - C + 0
                B = V - C + C 
            elif HH < 6:
                R = V - C + C
                G = V - C + 0
                B = V - C + X
            else:
                R = V - C + 0
                G = V - C + 0
                B = V - C + 0
            rgbt[i][j][0] = R
            rgbt[i][j][1] = G
            rgbt[i][j][2] = B
    rgbt = rgbt * 255
    return rgbt.astype(np.uint8)

def revhue(imag):
    rh = imag.copy()
    rh[:,:,0] = 180.0 + imag[:,:,0]
    rh = rh - 360.0*(rh > 360)
    return rh
show(hsv2rgb(revhue(rgb2hsv(img))))


In [142]:
#Q6
def decrease_color2(imag):
    dc = imag.copy().astype(np.uint16)
    base = dc.copy()
    base[:,:,:] = 0

    base = base + (dc < 64) * 32
    dc = dc + (dc < 64) * 512

    base = base + (dc < 128) * 96
    dc = dc + (dc < 128) * 512

    base = base + (dc < 192) * 160
    dc = dc + (dc < 192) * 512

    base = base + (dc < 256) * 224
    dc = dc + (dc < 256) * 512
    return base.astype(np.uint8)

def decrease_color(imag):
    dc = imag.copy()
    dc = dc // 64
    dc = dc * 64 + 32
    return dc

show(decrease_color(img))


In [143]:
show(decrease_color2(img))

In [144]:
img = load("imori_128x128.png")

In [145]:
show(img)

In [161]:
#Q7
def avg_pooling2(imag, poolsize=8):
    poo = imag.copy()
    for i in range(0, poo.shape[0], poolsize):
        for j in range(0, poo.shape[1], poolsize):
            total = np.zeros(3).astype(np.uint32)
            for p in range(i, i+poolsize):
                for q in range(j, j+poolsize):
                    total = total + poo[p][q]
            total = total // (poolsize*poolsize)
            for p in range(i, i+poolsize):
                for q in range(j, j+poolsize):
                    poo[p][q] = total
    return poo

def avg_pooling(imag, G=8):
    out = imag.copy()

    H, W, C = imag.shape
    Nh = int(H / G)
    Nw = int(W / G)

    for y in range(Nh):
        for x in range(Nw):
            for c in range(C):
                out[G*y:G*(y+1), G*x:G*(x+1), c] = np.mean(out[G*y:G*(y+1), G*x:G*(x+1), c]).astype(np.int)
    
    return out

show(avg_pooling2(img))

In [164]:
#Q8
def max_pooling2(imag, poolsize=8):
    poo = imag.copy()
    for i in range(0, poo.shape[0], poolsize):
        for j in range(0, poo.shape[1], poolsize):
            mx = np.zeros(3).astype(np.uint8)
            for p in range(i, i+poolsize):
                for q in range(j, j+poolsize):
                    mx[0] = max(mx[0], poo[p][q][0])
                    mx[1] = max(mx[1], poo[p][q][1])
                    mx[2] = max(mx[2], poo[p][q][2])
            for p in range(i, i+poolsize):
                for q in range(j, j+poolsize):
                    poo[p][q] = mx
    return poo

def max_pooling(imag, G=8):
    # Max Pooling
    out = imag.copy()

    H, W, C = imag.shape
    Nh = int(H / G)
    Nw = int(W / G)

    for y in range(Nh):
        for x in range(Nw):
            for c in range(C):
                out[G*y:G*(y+1), G*x:G*(x+1), c] = np.max(out[G*y:G*(y+1), G*x:G*(x+1), c])
    return out

show(max_pooling2(img))

In [120]:
#Q9
def gaussian_filter(imag, around=1, sigma=1.3):
    gf = imag.copy()
    result = imag.copy()
    
    w = np.zeros([2*around+1, 2*around+1], dtype=np.float)
    for s in range(2*around+1):
        for t in range(2*around+1):
            w[s][t] = np.exp(-1.0*((s-around)*(s-around)+(t-around)*(t-around))/(2.0*sigma*sigma)) / (2.0*np.pi*sigma*sigma)
    w = w / w.sum()
    for i in range(gf.shape[0]):
        for j in range(gf.shape[1]):
            p = np.zeros(3).astype(np.float)
            for s in range(2*around+1):
                for t in range(2*around+1):
                    if 0 <= i + s - around < gf.shape[0] and 0 <= j + t - around < gf.shape[1]:
                        p += gf[i+s-around][j+t-around] * w[s,t]
            result[i][j] = p.astype(np.uint8)
    return result

nimg = load("imori_256x256_noise.png")

show(gaussian_filter(nimg))

In [184]:
show(nimg)

In [169]:
show(gaussian_filter(nimg, 4))

KeyboardInterrupt: 

In [170]:
show(gaussian_filter(nimg))

In [190]:
show(gaussian_filter(nimg,2))

In [191]:
show(gaussian_filter(nimg,1,2))

In [192]:
show(gaussian_filter(nimg,1,4.0))

In [193]:
show(gaussian_filter(nimg,1,1.3))

In [194]:
show(gaussian_filter(nimg,1,0.1))

In [196]:
show(gaussian_filter(nimg,2,20.0))

In [197]:
show(gaussian_filter(nimg,2,1.1))

In [221]:
#Q10
def median_filter(imag, around=1):
    gf = imag.copy()
    result = imag.copy()
    
    for i in range(gf.shape[0]):
        for j in range(gf.shape[1]):
            r = []
            g = []
            b = []
            for s in range(i-around, i+around+1):
                for t in range(j-around, j+around+1):
                    if 0 <= s < gf.shape[0] and 0 <= t < gf.shape[1]:
                        r.append(gf[s,t,0])
                        g.append(gf[s,t,1])
                        b.append(gf[s,t,2])
            size = len(r)
            pt = np.zeros(3).astype(np.uint32)
            if size % 2 == 0:
                rr = np.array(sorted(r), dtype=np.int32)
                gg = np.array(sorted(g), dtype=np.int32)
                bb = np.array(sorted(b), dtype=np.int32)
                pt[0] = (rr[size//2] + rr[-1+size//2])//2
                pt[1] = (gg[size//2] + gg[-1+size//2])//2
                pt[2] = (bb[size//2] + bb[-1+size//2])//2
            else:
                pt[0] = sorted(r)[size//2]
                pt[1] = sorted(g)[size//2]
                pt[2] = sorted(b)[size//2]
            result[i][j] = pt.astype(np.uint8)
    return result


In [202]:
show(nimg)

In [222]:
show(median_filter(nimg))

In [223]:
show(median_filter(nimg,2))

In [224]:
show(median_filter(nimg,4))

In [9]:
#Q11
def smoothing_filter(imag, around=2):
    sf = imag.copy()
    result = imag.copy().astype(np.int32)
    
    for i in range(sf.shape[0]):
        for j in range(sf.shape[1]):
            r = 0
            g = 0
            b = 0
            size = 0
            for s in range(i-around, i+around+1):
                for t in range(j-around, j+around+1):
                    if 0 <= s < sf.shape[0] and 0 <= t < sf.shape[1]:
                        size += 1
                        r += sf[s,t,0]
                        g += sf[s,t,1]
                        b += sf[s,t,2]
            result[i,j] = np.array([r,g,b]).astype(np.int32) // size
    
    return result.astype(np.uint8)

show(smoothing_filter(nimg))

In [10]:
show(smoothing_filter(nimg, 3))

In [15]:
#Q12
def motion_filter(imag, around=2):
    sf = imag.copy()
    result = imag.copy().astype(np.int32)
    
    for i in range(sf.shape[0]):
        for j in range(sf.shape[1]):
            r = 0
            g = 0
            b = 0
            size = 0
            for s in range(i-around, i+around+1):
                t = j+(i-s)
                if 0 <= s < sf.shape[0] and 0 <= t < sf.shape[1]:
                    size += 1
                    r += sf[s,t,0]
                    g += sf[s,t,1]
                    b += sf[s,t,2]
            result[i,j] = np.array([r,g,b]).astype(np.int32) // size
    return result.astype(np.uint8)

show(motion_filter(img))    

In [37]:
#Q13

def maxmin_filter(imag, around=1):
    mf = gray_scale_single(imag)
    result = mf.copy().astype(np.int32)
    
    for i in range(mf.shape[0]):
        for j in range(mf.shape[1]):
            vmax = -1
            vmin = 257
            for s in range(i-around, i+around+1):
                for t in range(j-around, j+around+1):
                    if 0 <= s < mf.shape[0] and 0 <= t < mf.shape[1]:
                        v = mf[s,t]
                        vmax = max(vmax, v)
                        vmin = min(vmin, v)
            result[i,j] = vmax - vmin
            
    return gray_scale_triple(result.astype(np.uint8))

show(maxmin_filter(img, 2))

In [51]:
#Q14
def differential_filter_horizontal(imag):
    df = gray_scale_single(imag).astype(np.int32)
    result = df.copy().astype(np.int32)
    
    for i in range(df.shape[0]):
        for j in range(df.shape[1]):
            if j > 0:
                result[i,j] = df[i,j] - df[i,j-1]
            else:
                result[i,j] = df[i,j] 
            result[i,j] = np.min([result[i,j],255])
            result[i,j] = np.max([result[i,j],0])          
    return gray_scale_triple(result.astype(np.uint8))

show(differential_filter_horizontal(img))

In [50]:
def differential_filter_vertical(imag):
    df = gray_scale_single(imag).astype(np.int32)
    result = df.copy().astype(np.int32)
    
    for i in range(df.shape[0]):
        for j in range(df.shape[1]):
            if i > 0:
                result[i,j] = df[i,j] - df[i-1,j]
            else:
                result[i,j] = df[i,j]
            result[i,j] = np.min([result[i,j],255])
            result[i,j] = np.max([result[i,j],0])          
    return gray_scale_triple(result.astype(np.uint8))

show(differential_filter_vertical(img))

In [57]:
#Q15
def prewitt_filter_vertical(imag, around=1):
    df = gray_scale_single(imag).astype(np.int32)
    result = df.copy().astype(np.int32) * 0

    imax = df.shape[0] - 1
    jmax = df.shape[1] - 1
    for i in range(df.shape[0]):
        for j in range(df.shape[1]):
            top = i - around
            bottom = i + around
            for t in range(j-around, j+around+1):
                if 0 <= top <= imax and 0 <= t <= jmax:
                    result[i,j] += df[top,t]
                if 0 <= bottom <= imax and 0 <= t <= jmax:
                    result[i,j] -= df[bottom,t]
            result[i,j] = np.min([result[i,j],255])
            result[i,j] = np.max([result[i,j],0])          
    return gray_scale_triple(result.astype(np.uint8))

show(prewitt_filter_vertical(img))

In [58]:
def prewitt_filter_horizontal(imag, around=1):
    df = gray_scale_single(imag).astype(np.int32)
    result = df.copy().astype(np.int32) * 0

    imax = df.shape[0] - 1
    jmax = df.shape[1] - 1
    for i in range(df.shape[0]):
        for j in range(df.shape[1]):
            left = j - around
            right = j + around
            for s in range(i-around, i+around+1):
                if 0 <= s <= imax and 0 <= left <= jmax:
                    result[i,j] += df[s,left]
                if 0 <= s <= imax and 0 <= right <= jmax:
                    result[i,j] -= df[s, right]
            result[i,j] = np.min([result[i,j],255])
            result[i,j] = np.max([result[i,j],0])          
    return gray_scale_triple(result.astype(np.uint8))

show(prewitt_filter_horizontal(img))

In [107]:
#Q16
def apply_gs_filter(imag, filt, base=0):
    gs = gray_scale_single(imag).astype(np.int32)
    result = (gs.copy() * 0 + 1) * base
    around = filt.shape[0] // 2
    imax = gs.shape[0] - 1
    jmax = gs.shape[1] - 1
    for i in range(gs.shape[0]):
        for j in range(gs.shape[1]):
            for s in range(i-around, i+around+1):
                for t in range(j-around, j+around+1):
                    if 0 <= s <= imax and 0 <= t <= jmax:
                        result[i,j] += gs[s,t] * filt[s-i+around,t-j+around]
    return gray_scale_triple(np.clip(result, 0, 255).astype(np.uint8))

def sobel_filter_horizontal(imag, around=1):
    filt = np.zeros([2*around+1, 2*around+1]).astype(np.int32)
    left = 0
    right = filt.shape[1]-1
    for i in range(filt.shape[0]):
        filt[i,left] = 1
        filt[i,right] = -1
    filt[around,left] = 2
    filt[around,right] = -2
    return apply_gs_filter(imag, filt)

def sobel_filter_vertical(imag, around=1):
    filt = np.zeros([2*around+1, 2*around+1]).astype(np.int32)
    top = 0
    bottom = filt.shape[0]-1
    for j in range(filt.shape[1]):
        filt[top,j] = 1
        filt[bottom, j] = -1
    filt[top, around] = 2
    filt[bottom, around] = -2
    return apply_gs_filter(imag, filt)



In [109]:
show(sobel_filter_horizontal(img))

In [110]:
show(sobel_filter_vertical(img))

In [117]:
#Q17
def laplacian_filter(imag):
    filt = np.array([
        [0,1,0],
        [1,-4,1],
        [0,1,0]
    ]).astype(np.int32)
    return apply_gs_filter(imag, filt)


show(laplacian_filter(img128))

In [118]:
#Q18
def emboss_filter(imag):
    filt = np.array([
        [-2,-1,0],
        [-1,1,1],
        [0,1,2]
    ]).astype(np.int32)
    return apply_gs_filter(imag, filt)


show(emboss_filter(img128))

In [128]:
#Q19
def log_filter(imag, around=2, sigma=3.0):
    gf = imag.copy()
    result = imag.copy()
    
    w = np.zeros([2*around+1, 2*around+1], dtype=np.float)
    for s in range(2*around+1):
        for t in range(2*around+1):
            w[s][t] = ((s-around)*(s-around)+(t-around)*(t-around)-2.0*sigma*sigma) * np.exp(-1.0*((s-around)*(s-around)+(t-around)*(t-around))/(2.0*sigma*sigma)) / (2.0*np.pi*sigma*sigma*sigma*sigma*sigma*sigma)
    w = w / w.sum()
    for i in range(gf.shape[0]):
        for j in range(gf.shape[1]):
            p = np.zeros(3).astype(np.float)
            for s in range(2*around+1):
                for t in range(2*around+1):
                    if 0 <= i + s - around < gf.shape[0] and 0 <= j + t - around < gf.shape[1]:
                        p += gf[i+s-around][j+t-around] * w[s,t]
            result[i][j] = p.astype(np.uint8)
    return result

show(log_filter(nimg))

In [131]:
dimg.ravel()

array([ 82,  92, 107, ...,  84,  89, 108], dtype=uint8)

In [133]:
plt.hist(dimg.ravel())

(array([  119.,  9425., 22104., 31701., 29986., 29249., 34072., 23488.,
        10990.,  5474.]),
 array([ 71. ,  77.9,  84.8,  91.7,  98.6, 105.5, 112.4, 119.3, 126.2,
        133.1, 140. ]),
 <BarContainer object of 10 artists>)

In [135]:
plt.hist(dimg.ravel(),bins=255,rwidth=0.8,range=(0,255))
plt.show()

In [137]:
len(dimg.ravel())

196608

In [138]:
dimg.min()

71

In [139]:
dimg.max()


140

In [145]:
#Q21
def hist_norm(imag):
    org = imag.copy().astype(np.float)
    a = 0.0
    b = 255.0
    c = org.min()
    d = org.max()
    result = ((b-a)/(d-c)) * (org - c) + a
    return np.clip(result, 0, 255).astype(np.uint8)

show(hist_norm(dimg))

In [146]:
show(dimg)

In [152]:
#Q22
def hist_scaleshift(imag):
    org = imag.copy().astype(np.float)
    flt = org.flatten()
    m = flt.mean()
    s = flt.std()
    s0 = 52.0
    m0 = 128.0
    result = org.copy()*0
    result = (s0/s) * (org - m) + m0
    return np.clip(result, 0, 255).astype(np.uint8)

show(hist_scaleshift(dimg))
    

In [173]:
plt.hist(hist_scaleshift(dimg).flatten(),bins=255)
plt.show()

In [174]:
plt.hist(hist_norm(dimg).flatten(),bins=255)
plt.show()

In [180]:
#Q23
def hist_equalization(imag):
    org = imag.copy().astype(np.float)
    flt = org.flatten()
    h = np.zeros(256).astype(np.float)
    for f in flt:
        h[int(f)] += 1
    zmax = 255.0
    s = len(flt)
    
    zz = np.zeros(256).astype(np.float)
    for z in range(256):
        zz[z] = h[0:z+1].sum()
    zz = (zmax/s) * zz

    result = org.copy() * 0
    for s in range(org.shape[0]):
        for t in range(org.shape[1]):
            for u in range(org.shape[2]):
                 result[s,t,u] = zz[int(org[s,t,u])]
    return np.clip(result, 0, 255).astype(np.uint8)

show(hist_equalization(dimg))
    

In [181]:
plt.hist(hist_equalization(dimg).flatten(),bins=255)
plt.show()

In [183]:
show(hist_equalization(img128))

In [182]:
plt.hist(hist_equalization(img128).flatten(),bins=255)
plt.show()

In [187]:
#Q24
def gamma_correction(imag):
    org = imag.copy().astype(np.float) / 255.0   
    g = 2.2
    c = 1.0
    result = ((1.0/c) * org) ** (1.0/g)
    result = result * 255.0
    return np.clip(result, 0, 255).astype(np.uint8)

show(gamma_correction(gimg))
    

In [188]:
show(gimg)